DROP TABLE IF EXISTS guests;
DROP TABLE IF EXISTS events;


CREATE TABLE guests (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  has_attended BOOLEAN
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  location VARCHAR(255)
);
